GET http://localhost:3001/api/blogs
###

POST http://localhost:3001/api/blogs
content-type: application/json

{
        "title": "Harry Potter y la cámara secreta",
        "author": "Rowling, J. K.",
        "url": "https://www.crisol.com.pe/catalogsearch/result/?q=+Harry+Potter+y+la+c%C3%A1mara+secreta",
        "likes": 3
}
###

POST http://localhost:3001/api/blogs
content-type: application/json

{
        "title": "Harry Potter y la piedra filosofal",
        "author": "Rowling, J. K.",
        "url": "https://www.crisol.com.pe/catalogsearch/result/?q=+Harry+potter+y+la+piedra+filosofal",
        "likes": 2
}
###

POST http://localhost:3001/api/users
content-type: application/json

{
        "username": "Solidus",
        "name": "George Sears",
        "password": "secret"
}
###

POST http://localhost:3001/api/users
content-type: application/json

{
        "username": "Joker",
        "name": "Ren Amamiya",
        "password": "secret"
}
###
GET http://localhost:3001/api/users

###

DELETE http://localhost:3001/api/blogs/2
###

GET http://localhost:3001/api/blogs/66bc106f185997c07b596fdd
###